# coding: utf-8
"""
Shortcut manager.

Coordinate keyboard and mouse shortcuts with:
1. Multiple concurrent shortcut tasks.
2. Isolation between keys.
3. Protection against recapturing restored keys.
4. Hold and toggle recording modes.
"""
from __future__ import annotations

from core.i18n import Notice
import time
from concurrent.futures import ThreadPoolExecutor
from typing import TYPE_CHECKING, Dict, List, Optional

from pynput import keyboard, mouse

from . import logger
from core.client.shortcut.key_mapper import *
from core.client.shortcut.key_mapper import KeyMapper
from core.client.shortcut.emulator import ShortcutEmulator
from core.client.shortcut.event_handler import ShortcutEventHandler
from core.client.shortcut.task import ShortcutTask

if TYPE_CHECKING:
    from core.client.shortcut.shortcut_config import Shortcut
    from core.client.state import ClientState
    from core.client.app import CapsWriterClient



class ShortcutManager:
    """
    Shortcut manager.

    Use pynput to listen for multiple keyboard and mouse shortcuts.
    Handle input through win32_event_filter to minimize dispatch overhead.
    """

    def __init__(self, app: CapsWriterClient, shortcuts: List[Shortcut]):
        """
        Initialize shortcut management.

        Args:
            app: Client App instance.
            shortcuts: Shortcut configurations.
        """
        self.app = app
        self.shortcuts = shortcuts

        # Input listeners.
        self.keyboard_listener: Optional[keyboard.Listener] = None
        self.mouse_listener: Optional[mouse.Listener] = None

        # Map key names to ShortcutTask instances.
        self.tasks: Dict[str, ShortcutTask] = {}

        # Thread pool.
        self._pool = ThreadPoolExecutor(max_workers=4)

        # Input emulator.
        self._emulator = ShortcutEmulator()

        # Track key restoration.
        self._restoring_keys = set()

        # Event handler.
        self._event_handler = ShortcutEventHandler(self.tasks, self._pool, self._emulator)

        # Initialize shortcut tasks.
        self._init_tasks()

    @property
    def state(self) -> ClientState:
        """Access shared client state."""
        return self.app.state

    def _init_tasks(self) -> None:
        """Initialize all shortcut tasks."""
        from config_client import ClientConfig as Config

        for shortcut in self.shortcuts:
            if not shortcut.enabled:
                continue

            task = ShortcutTask(self.app, shortcut)
            task._manager_ref = lambda: self  # Manager accessor for callbacks.
            task.pool = self._pool
            task.threshold = shortcut.get_threshold(Config.threshold)
            self.tasks[shortcut.key] = task

    # Listener creation.

    def create_keyboard_filter(self):
        """Create the keyboard event filter."""
        def win32_event_filter(msg, data):
            # Handle only KEYDOWN and KEYUP messages.
            if msg not in KEYBOARD_MESSAGES:
                return True

            key_name = KeyMapper.vk_to_name(data.vkCode)

            # Ignore events generated by this application.
            if self._check_emulating(key_name, msg):
                return True
            if self._check_restoring(key_name, msg):
                return True

            # Find the matching shortcut.
            if key_name not in self.tasks:
                return True

            task = self.tasks[key_name]

            # Handle the key event.
            if msg in KEY_DOWN_MESSAGES:
                self._event_handler.handle_keydown(key_name, task)
            elif msg in KEY_UP_MESSAGES:
                self._event_handler.handle_keyup(key_name, task)

            # Suppress the event.
            if task.shortcut.suppress and self.keyboard_listener:
                self.keyboard_listener.suppress_event()

            return True

        return win32_event_filter

    def create_mouse_filter(self):
        """Create the mouse event filter."""
        def win32_event_filter(msg, data):
            # Handle only XBUTTON messages.
            if msg not in MOUSE_MESSAGES:
                return True

            # Extract the button identifier.
            xbutton = (data.mouseData >> 16) & 0xFFFF
            button_name = 'x1' if xbutton == XBUTTON1 else 'x2'

            # Ignore events generated by this application.
            if self._check_emulating(button_name, msg, is_mouse=True):
                return True

            # Find the matching shortcut.
            if button_name not in self.tasks:
                return True

            task = self.tasks[button_name]

            # Handle the mouse event.
            if msg == WM_XBUTTONDOWN:
                self._event_handler.handle_keydown(button_name, task)
            elif msg == WM_XBUTTONUP:
                self._handle_mouse_keyup(button_name, task)

            # Suppress the event.
            if task.shortcut.suppress and self.mouse_listener:
                self.mouse_listener.suppress_event()

            return True

        return win32_event_filter

    def _handle_mouse_keyup(self, button_name: str, task) -> None:
        """Handle a mouse button release."""
        # Toggle mode.
        if not task.shortcut.hold_mode:
            if task.pressed:
                task.pressed = False
                task.released = True
                task.event.set()
            return

        # Hold mode.
        if not task.is_recording:
            return

        duration = time.time() - task.recording_start_time
        logger.debug(Notice('diagnostic.shortcut_manager.key_released_after_s', value0=button_name, value1=duration))

        if duration < task.threshold:
            task.cancel()
            if task.shortcut.suppress:
                logger.debug(Notice('diagnostic.shortcut_manager.asynchronous_mouse_button_replay_scheduled', value0=button_name))
                self._pool.submit(self._emulator.emulate_mouse_click, button_name)
        else:
            task.finish()

    # Key restoration.

    def schedule_restore(self, key: str) -> None:
        """
        Schedule delayed key restoration without blocking the event handler.

        Args:
            key: Key to restore.

        Clear the flag only on release in _check_restoring;
        clearing it early from a worker could allow duplicate input on the main thread.
        """
        from pynput import keyboard

        self._restoring_keys.add(key)

        def do_restore():
            import time
            time.sleep(0.05)  # Delay 50 ms.
            if key == 'caps_lock':
                controller = keyboard.Controller()
                controller.press(keyboard.Key.caps_lock)
                controller.release(keyboard.Key.caps_lock)

        self._pool.submit(do_restore)

    def is_restoring(self, key: str) -> bool:
        """Return whether the specified key is being restored."""
        return key in self._restoring_keys

    def clear_restoring_flag(self, key: str) -> None:
        """Clear the restoration flag."""
        self._restoring_keys.discard(key)

    # Synthetic input filtering.

    def _check_emulating(self, key_name: str, msg: int, is_mouse: bool = False) -> bool:
        """Return whether a key is being simulated."""
        if not self._emulator.is_emulating(key_name):
            return False

        # Clear the flag on release.
        if is_mouse:
            if msg == WM_XBUTTONUP:
                self._emulator.clear_emulating_flag(key_name)
        else:
            if msg in (WM_KEYUP, WM_SYSKEYUP):
                self._emulator.clear_emulating_flag(key_name)

        return True  # Allow the event.

    def _check_restoring(self, key_name: str, msg: int) -> bool:
        """Return whether a key is being restored."""
        if not self.is_restoring(key_name):
            return False

        if msg in (WM_KEYUP, WM_SYSKEYUP):
            self.clear_restoring_flag(key_name)

        return True  # Allow the event.

    # Public interface.

    def start(self) -> None:
        """Start all listeners."""
        has_keyboard = any(s.type == 'keyboard' for s in self.shortcuts if s.enabled)
        has_mouse = any(s.type == 'mouse' for s in self.shortcuts if s.enabled)

        if has_keyboard:
            if self.keyboard_listener and self.keyboard_listener.is_alive():
                logger.debug(Notice('diagnostic.shortcut_manager.keyboard_listener_already_running_startup_skipped'))
            else:
                self.keyboard_listener = keyboard.Listener(
                    win32_event_filter=self.create_keyboard_filter()
                )
                self.keyboard_listener.start()
                logger.info(Notice('diagnostic.shortcut_manager.keyboard_listener_started'))

        if has_mouse:
            if self.mouse_listener and self.mouse_listener.is_alive():
                logger.debug(Notice('diagnostic.shortcut_manager.mouse_listener_already_running_startup_skipped'))
            else:
                self.mouse_listener = mouse.Listener(
                    win32_event_filter=self.create_mouse_filter()
                )
                self.mouse_listener.start()
                logger.info(Notice('diagnostic.shortcut_manager.mouse_listener_started'))

        # Display enabled shortcuts.
        for shortcut in self.shortcuts:
            if shortcut.enabled:
                mode = Notice('shortcut.hold' if shortcut.hold_mode else 'shortcut.click')
                toggle = Notice('shortcut.toggle' if shortcut.is_toggle_key() else 'shortcut.normal')
                logger.info(Notice('diagnostic.shortcut_manager.mode_suppress', value0=shortcut.key, value1=mode, value2=shortcut.suppress, value3=toggle))

    def stop(self) -> None:
        """Stop listeners and release resources."""
        if self.keyboard_listener:
            try:
                self.keyboard_listener.stop()
                logger.debug(Notice('diagnostic.shortcut_manager.keyboard_listener_stopped'))
            except Exception:
                pass
            finally:
                self.keyboard_listener = None
                
        if self.mouse_listener:
            try:
                self.mouse_listener.stop()
                logger.debug(Notice('diagnostic.shortcut_manager.mouse_listener_stopped'))
            except Exception:
                pass
            finally:
                self.mouse_listener = None

        # Cancel all tasks.
        for task in self.tasks.values():
            task.close()

        # Shut down the thread pool.
        self._pool.shutdown(wait=False)
        logger.debug(Notice('diagnostic.shortcut_manager.shortcut_manager_thread_pool_closed'))
